version: "3"

services:
  # Proxy
  proxy:
    image: nginx
    ports:
      - "8080:8080"
      - "8090:8090"
    networks:
      - chirpstack
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chirpstack-01
      - chirpstack-02
  # ChirpStack Network Server 01
  chirpstack-01:
    image: chirpstack/chirpstack:4.0.2
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./.docker/chirpstack:/etc/chirpstack
    depends_on:
      - postgres
      - mosquitto
      - redis
    networks:
      - chirpstack
  # ChirpStack Network Server 02
  chirpstack-02:
    image: chirpstack/chirpstack:4.0.2
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./.docker/chirpstack:/etc/chirpstack
    depends_on:
      - postgres
      - mosquitto
      - redis
    networks:
      - chirpstack
  # ChirpStack Gateway Bridge
  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4.0.0
    ports:
      - 1700:1700/udp
    volumes:
      - ./.docker/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto
    networks:
      - chirpstack
  # ChirpStack REST API
  chirpstack-rest-api-01:
    image: chirpstack/chirpstack-rest-api:4.0.0
    environment:
      - SERVER=proxy::8000
      - BIND=0.0.0.0:8090
      - INSECURE=true
    networks:
      - chirpstack
  # ChirpStack REST API 02
  chirpstack-rest-api-02:
    image: chirpstack/chirpstack-rest-api:4.0.0
    environment:
      - SERVER=proxy:8000
      - BIND=0.0.0.0:8090
      - INSECURE=true
    networks:
      - chirpstack
  # PostgreSQL
  postgres:
    image: postgres:14-alpine
    volumes:
      - ./.docker/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - chirpstack
    ports:
      - 5431:5432
  # Redis Server
  redis:
    image: redis:7-alpine
    volumes:
      - redisdata:/data
    networks:
      - chirpstack
    ports:
      - 6378:6379
  # Mosquitto
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./.docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - chirpstack
volumes:
  postgresqldata:
  redisdata:


networks:
  chirpstack:
    driver: bridge
